- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/AccountingController.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/OrderDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/accounting/AccountingSlipDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/accounting/AccountingSlipRowDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/accounting/OrderItemAccountingDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/transformer/AccountingSlipRowTransformer.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/transformer/AccountingSlipTransformer.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/Order.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/accounting/AccountingSlip.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/accounting/AccountingSlipRow.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/repository/jpa/AccountingSlipRepository.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/repository/jpa/AccountingSlipRowRepository.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/repository/jpa/OrderAccountingRepository.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/repository/jpa/OrderItemAccountingRepository.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/repository/jpa/OrderRepository.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/AccountingSlipService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/OrderAccountingService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/OrderItemAccountingService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/order/OrderService.java
Tositetason tiedot toistaiseksi kovakoodattuna (esim. CompanyCode, HeaderText), tarkennetaan vielä miten tiedot muodostetaan ja muutetaan toteutus sen mukaan
> KYV-88 implemented creating accounting data

- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/SubscriptionController.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/subscription/GetSubscriptionQuery.java
> KYV-414 : Cancel path of subscription returns SubscriptionDto.

- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/renewal/SubscriptionRenewalService.java
> KYV-445 : Fixes page start to start from right index.

- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/PaymentAdminController.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/service/OnlinePaymentService.java
> KYV-445 : Decrypting card token before calling visma endpoint.

- cartapi/pom.xml
- common/pom.xml
- eventsapi/pom.xml
- messageapi/pom.xml
- mockproductmanagement/pom.xml
- orderapi/pom.xml
- paymentapi/pom.xml
- pom.xml
- priceapi/pom.xml
- productapi/pom.xml
- productmapping/pom.xml
> KYV-444 : Updated dependency to 2.16.0

- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/logic/CardTokenFetcher.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/logic/ChargeCardTokenLogic.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/logic/TokenFetcher.java
> KYV-460 : Added visma pay request logging.

- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/OnlinePaymentController.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/data/PaymentReturnDto.java
> KYV-434 : Added new field paymentType to PaymentReturnDto.

- common/src/main/java/fi/hel/verkkokauppa/common/util/DateTimeUtil.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/admin/SubscriptionAdminController.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/order/OrderServiceTest.java
https://github.com/City-of-Helsinki/verkkokauppa-core/pull/144
That pr should be merged before this pr.
> KYV-505 - feature/KYV-505-allow-subscription-to-be-renewed

- common/src/main/java/fi/hel/verkkokauppa/common/configuration/ServiceConfigurationKeys.java
- common/src/main/java/fi/hel/verkkokauppa/common/util/DateTimeUtil.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/api/merchant/MerchantController.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/service/MerchantService.java
- merchantapi/src/test/java/fi/hel/verkkokauppa/configuration/api/merchant/MerchantControllerUnitTest.java
- merchantapi/src/test/java/fi/hel/verkkokauppa/configuration/api/namespace/NamespaceControllerUnitTest.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/AccountingExportController.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/OrderDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/accounting/AccountingExportDataDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/accounting/AccountingSlipDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/accounting/OrderAccountingDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/Order.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/accounting/AccountingExportData.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/accounting/AccountingSlip.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/accounting/OrderAccounting.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/AccountingExportDataService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/AccountingExportService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/AccountingSlipService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/OrderAccountingService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/order/OrderService.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/api/data/DummyData.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/accounting/AccountingSlipServiceTests.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/order/OrderServiceTest.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/test/utils/TestUtils.java
Refactored all accounting related models to use LocalData or LocalDateTime fields for date(time) fields that are String type.
> [KYV-682] refactor accounting date time string fields to local date time

- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/invoice/InvoiceServiceTest.java
> [KYV-682] Added a true assertion test.

- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/invoice/InvoiceServiceUnitTest.java
Added AutoConfigureMockMvc annotation.
> [KYV-682] Added AutoConfigureMockMvc annotation.

- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/invoice/InvoiceServiceUnitTest.java
Switched MockBean annotation to mockitos Mock and InjectMocks.
> [KYV-682] Switched MockBean annotation to mockitos Mock and InjectMocks.

- orderapi/src/test/java/fi/hel/verkkokauppa/order/api/admin/SubscriptionAdminControllerTest.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/api/admin/SubscriptionAdminControllerUnitTest.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/api/data/ControllerEventTests.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/api/data/SubscriptionControllerTests.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/id/IncrementIdTest.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/invoice/InvoiceServiceTest.java
Added RunIfProfile annotation to all funcitonal tests.
> [KYV-682] Added RunIfProfile annotation to all funcitonal tests.

- common/src/main/java/fi/hel/verkkokauppa/common/queue/config/FactoryConfiguration.java
- common/src/main/java/fi/hel/verkkokauppa/common/queue/error/DefaultActiveMQErrorHandler.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/listeners/DeadLetterQueueListener.java
Added some logging for DLQ queue listener.
> [KYV-731] Added some logging for DLQ queue listener.

- common/src/main/java/fi/hel/verkkokauppa/common/queue/error/DefaultActiveMQErrorHandler.java
Added prefix for default activemq error handler log.
> [KYV-731] Added prefix for default activemq error handler log.

- orderapi/src/main/java/fi/hel/verkkokauppa/order/listeners/DeadLetterQueueListener.java
Added more detailed logging and some null checks.
> [KYV-731] Added more detailed logging and some null checks.

- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/accounting/AccountingExportService.java
Fixed variable names to be more describing.
> [KYV-745] Fixed variable names to be more describing.

- common/src/main/java/fi/hel/verkkokauppa/common/configuration/ServiceConfigurationKeys.java
- merchantapi/src/test/java/fi/hel/verkkokauppa/configuration/api/merchant/MerchantControllerTest.java
- merchantapi/src/test/java/fi/hel/verkkokauppa/configuration/api/merchant/MerchantControllerUnitTest.java
Added new merchant configuration key merchantShopId.
> [KYV-700] Added new merchant configuration key merchantShopId.

- merchantapi/src/test/java/fi/hel/verkkokauppa/configuration/api/namespace/NamespaceControllerUnitTest.java
Fixed unit test by adding merchant service dependency.
> [KYV-719] Fixed unit test by adding merchant service dependency.

- common/src/main/java/fi/hel/verkkokauppa/common/rest/CommonServiceConfigurationClient.java
- common/src/main/java/fi/hel/verkkokauppa/common/rest/dto/configuration/ConfigurationDto.java
- common/src/main/java/fi/hel/verkkokauppa/common/rest/dto/configuration/LocaleDto.java
- common/src/main/java/fi/hel/verkkokauppa/common/rest/dto/configuration/MerchantDto.java
- common/src/main/java/fi/hel/verkkokauppa/common/util/ConfigurationParseUtil.java
- common/src/main/java/fi/hel/verkkokauppa/common/util/ListUtil.java
- infra/paymentapi/src/main/resources/application.properties
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/api/merchant/MerchantController.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/api/merchant/dto/ConfigurationDto.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/api/merchant/dto/LocaleDto.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/api/namespace/NamespaceController.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/mapper/ConfigurationMapper.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/service/MerchantService.java
- merchantapi/src/main/java/fi/hel/verkkokauppa/configuration/service/NamespaceService.java
- merchantapi/src/test/java/fi/hel/verkkokauppa/configuration/api/merchant/MerchantControllerUnitTest.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/test/utils/TestUtils.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/OnlinePaymentController.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/data/GetPaymentMethodListRequest.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/constant/GatewayEnum.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/logic/builder/PaymentContextBuilder.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/logic/builder/PaytrailPaymentContextBuilder.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/logic/context/PaytrailPaymentContext.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/paytrail/factory/PaytrailAuthClientFactory.java
- paymentapi/src/main/java/fi/hel/verkkokauppa/payment/service/PaymentPaytrailService.java
- paymentapi/src/main/resources/application-local.properties
- paymentapi/src/main/resources/application.properties
- paymentapi/src/test/java/fi/hel/verkkokauppa/payment/api/OnlinePaymentControllerTests.java
Enable payment api to fetch paytrail payment methods.
> [KYV-749] Enable payment api to fetch paytrail payment methods

- common/src/main/java/fi/hel/verkkokauppa/common/configuration/ServiceConfigurationKeys.java
Added refund redirect success url to namespace keys.
> [KYV-781] Added refund redirect success url to namespace keys.

- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/OrderController.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/FlowStepDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/api/data/OrderAggregateDto.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/mapper/FlowStepMapper.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/model/FlowStep.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/repository/jpa/FlowStepRepository.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/order/FlowStepService.java
- orderapi/src/main/java/fi/hel/verkkokauppa/order/service/order/OrderService.java
- orderapi/src/test/java/fi/hel/verkkokauppa/order/service/order/OrderServiceTest.java
Implemented new endpoint that saved flow steps by orderId.
> [KYV-739] Implemented new endpoint that saved flow steps by orderId.

- paymentapi/src/test/java/fi/hel/verkkokauppa/payment/api/PaytrailPaymentControllerUnitTests.java
Fixed paytrail payment controller unit tests.
> Fixed paytrail payment controller unit tests.

- cartapi/azure-pipelines.yaml
add variable deployToDrtest; remove parameter drtestDeployment
> add variable deployToDrtest; remove parameter
